In [10]:

print(np.__version__)
arr = np.array([1,2,3], ndmin = 5)
print(arr)
print(arr.ndim)
print(arr.shape)

1.26.4
[[[[[1 2 3]]]]]
5
(1, 1, 1, 1, 3)


In [3]:
import numpy as np

In [7]:
arr1 = np.array([[1,2, 3,4],[5,6,7,7]])
for x in np.nditer(arr1[ ::3]):
    print(x)

1
2
3
4


In [16]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [17]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis =1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [25]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)
print(newarr[0])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]


In [32]:
arr = np.array([[1,2],[3,4], [5,6], [7,8]])
spl_arr = np.array_split(arr, 2, axis =1)
print(spl_arr)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]
